Fix font-edit linking error: add -lm
The recent refactoring of sfit.c removed the custom sqrt() in favor of
using the standard library's sqrt() and fabs() functions. This requires
linking against the math library.

Link error:
  undefined reference to symbol 'sqrt@@GLIBC_2.2.5'
  DSO missing from command line: libm.so.6